[FredMDQD]
git-tree-sha1 = "989dbb3a62ac672e142ce50e03b32e89db200e90"
lazy = true

    [[FredMDQD.download]]
    url = "https://github.com/enweg/FredMDQD.jl/raw/artifacts/artifacts.tar.gz"
    sha256 = "5d84207e5c17ddff0b8e8f4dc0eb7ee748f9ca80650f076ae9ad23e1b3bd7c4b"
