[FredMDQD]
git-tree-sha1 = "02dd7c522091cfe8895fc757fc1affc1f4b195bb"
lazy = true

    [[FredMDQD.download]]
    url = "https://github.com/enweg/FredMDQD.jl/raw/artifacts/artifacts.tar.gz"
    sha256 = "5086ddf1f1f5c0450884f56ae96275683e7640da7f2cf3f8f67bfa8014f6feec"
